---
- name: Install dependencies
  ansible.builtin.include_tasks: install.yml
  tags:
    - config

- name: Configure
  tags:
    - config
  ansible.builtin.include_tasks: config.yml

- name: Setup contexts
  tags:
    - git
    - config
  include_tasks: "setup-context.yml"
  vars:
    name: "{{ item.key }}"
    context: "{{ item.value }}"
  loop: "{{ contexts | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
