- name: Ensure dir
  tags:
    - config
  ansible.builtin.file:
    path: "{{ context.path }}"
    state: directory
    owner: "{{ username }}"
    mode: "700"

- name: Setup context env
  tags:
    - config
  ansible.builtin.template:
    src: "../templates/envrc.context.j2"
    dest: "{{ context.path }}/.envrc"
    mode: "600"
  vars:
    env: "{{ context.env}}"
    name: "{{ name }}"
  when: "'env' in context"
