- name: Create group
  when: not mac_os
  become: true
  tags: always
  ansible.builtin.group:
    name: "{{ username }}"
    state: present

- name: Create user
  when: not mac_os
  become: true
  tags: always
  ansible.builtin.user:
    name: "{{ username }}"
    update_password: "on_create"
    create_home: yes
    group: "{{ username }}"

- name: Ensure home
  tags: always
  become: true
  ansible.builtin.file:
    path: "{{ home }}"
    state: directory
    owner: "{{ username }}"

- name: Install yay
  tags:
    - install
  when: archlinux
  include_tasks: yay.yml

- name: Install flatpak
  tags:
    - install
  when: archlinux
  include_tasks: flatpak.yml
