- name: Setting host facts
  tags: always
  ansible.builtin.set_fact:
    username: alice
    home: /Users/alice
    use_become: true
    mac_os: "{{ ansible_distribution == 'MacOSX' }}"
    contexts: "{{ ['default'] + (contexts | default([])) }}"
