---
software_starship_mirror: "https://github.com/starship/starship/releases/download/"
software_starship_version: v1.20.1
software_starship_arch_map:
  arm64: aarch64
  aarch64: aarch64
  x86_64: x86_64
software_starship_system_map:
  Darwin: apple-darwin
  Linux: unknown-linux-musl

software_starship_download_url: "{{ software_starship_mirror }}/{{ software_starship_version }}/starship-{{ software_starship_arch_map[ansible_architecture] }}-{{ software_starship_system_map[ansible_system] }}.tar.gz"
software_starship_download_dir: "/tmp/starship.tar.gz"
software_starship_unpack_dir: "/tmp/starship"
software_starship_unpack_file: "{{ software_starship_unpack_dir }}/starship"
