---
- name: Install core dependencies
  tags:
    - install
  ansible.builtin.package:
    name:
      - zsh

- name: Set shell
  become: true
  tags:
    - config
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /usr/bin/zsh

- name: Install context dependencies
  ansible.builtin.include_tasks: install.yml
  loop: "{{ contexts }}"
  loop_control:
    loop_var: context
  tags:
    - config

- name: Install atuin
  tags:
    - install
  include_role:
    name: software/atuin

- name: Install starship
  tags:
    - install
  include_role:
    name: software/starship

- name: Setup node
  tags:
    - config
    - install
  include_tasks: "nvm.yml"

- name: Setup nvim
  tags:
    - config
    - nvim
  include_tasks: "nvim.yml"

- name: Configure contexts
  ansible.builtin.include_tasks: config.yml
  loop: "{{ contexts }}"
  loop_control:
    loop_var: context
  tags:
    - config
