---
- name: Configure neovim
  tags:
    - config
    - nvim
  ansible.builtin.git:
    repo: https://github.com/morten-olsen/nvim
    dest: "{{ home }}/.config/nvim"
    accept_newhostkey: true
    clone: true
    update: true
    force: true

- name: Prepare neovim
  tags:
    - config
    - nvim
  register: nviminstall
  changed_when: "nviminstall.stdout != ''"
  ansible.builtin.shell: nvim --headless +q
  args:
    executable: /bin/bash
