---
- name: Ensure dir
  tags:
    - config
  ansible.builtin.file:
    path: "{{ home }}/.ssh"
    mode: "0700"
    owner: "{{ username }}"
    state: directory

- name: Setup config
  tags:
    - config
  ansible.builtin.template:
    src: "../templates/config.j2"
    dest: "{{ home }}/.ssh/config"
    owner: "{{ username }}"
    mode: "644"
