---
- name: "Load vars"
  ansible.builtin.include_vars: "{{ item }}"
  tags:
    - install
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - default.yml
      paths: ../vars
      skip: true

- name: "Install dependencies"
  become: "{{ install_with_root }}"
  tags:
    - install
  when: terminal_pkgs
  ansible.builtin.package:
    name: "{{ terminal_pkgs }}"

- name: "Install casks"
  tags:
    - install
  when: terminal_casks
  community.general.homebrew_cask:
    name: "{{ terminal_casks }}"
    state: installed
