---
- name: Install context dependencies
  ansible.builtin.include_tasks: install.yml
  loop: "{{ contexts }}"
  loop_control:
    loop_var: context
  tags:
    - config

- name: Install atuin
  tags:
    - install
  ansible.builtin.include_role:
    name: software_atuin

- name: Configure contexts
  ansible.builtin.include_tasks: config.yml
  loop: "{{ contexts }}"
  loop_control:
    loop_var: context
  tags:
    - config
