- name: Download starship
  tags: always
  become: "{{ use_become }}"
  ansible.builtin.get_url:
    mode: "0600"
    url: "{{ software_starship_download_url }}"
    dest: "{{ software_starship_download_dir }}"

- name: Create dir
  tags: always
  become: "{{ use_become }}"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ software_starship_unpack_dir }}"
    state: directory

- name: Extract starship
  tags: always
  become: "{{ use_become }}"
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ software_starship_download_dir }}"
    dest: "{{ software_starship_unpack_dir }}"

- name: Ensure dir
  tags: always
  become: "{{ use_become }}"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ home }}/.local/bin"
    owner: "{{ username }}"
    state: directory

- name: Move bin
  tags: always
  become: "{{ use_become }}"
  ansible.builtin.copy:
    remote_src: true
    mode: "0755"
    owner: "{{ username }}"
    src: "{{ software_starship_unpack_file }}"
    dest: "{{ home }}/.local/bin/starship"
